# Generated by Django 5.0 on 2025-04-28 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('endereco', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(20)])),
                ('cidade', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(50)])),
                ('estado', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
