# Generated by Django 5.0 on 2025-04-28 23:33

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_alter_cliente_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BAS', 'Básico'), ('STAND', 'PAdrão'), ('PREM', 'Premium'), ('MAS', 'Master')], default='STAND', max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('mensalidade', models.DecimalField(decimal_places=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('donwload', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)])),
                ('upload', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('franquia_dados', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('fidelidade', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 28, 23, 33, 26, 884971, tzinfo=datetime.timezone.utc))])),
                ('habilitado', models.BooleanField()),
                ('contratacao', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internet.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
