# Generated by Django 5.0 on 2025-04-28 23:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='fidelidade',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 28, 23, 34, 22, 443786, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='mensalidade',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
