# Generated by Django 5.0 on 2025-04-28 23:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0004_alter_assinatura_fidelidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='fidelidade',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 28))]),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='tipo',
            field=models.CharField(choices=[('BAS', 'Básico'), ('STAND', 'Padrão'), ('PREM', 'Premium'), ('MAS', 'Master')], default='STAND', max_length=10),
        ),
    ]
