# Generated by Django 5.1.6 on 2025-05-01 14:57

import internet.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0005_alter_assinatura_fidelidade_alter_assinatura_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='fidelidade',
            field=models.DateField(validators=[internet.validators.validators.validate_min_date_today]),
        ),
    ]
