# Generated by Django 5.1.6 on 2025-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0006_alter_assinatura_fidelidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinatura',
            old_name='donwload',
            new_name='download',
        ),
    ]
